# Generated by Django 5.1 on 2024-08-17 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='blog/images')),
                ('date', models.DateTimeField(verbose_name=datetime.date.today)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
